<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>TlsPoc.CrankServer</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TlsPoc.Core\TlsPoc.Core.csproj" />
  </ItemGroup>

</Project>
