<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TlsPoc.Benchmarks</RootNamespace>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TlsPoc.Core\TlsPoc.Core.csproj" />
  </ItemGroup>

</Project>
